name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:
  
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v1

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.88.0
          TARGET_REPO: thomux/thomux.github.io
          TARGET_BRANCH: page
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CNAME: thomux.eu
